In [23]:
from sklearn.datasets import make_regression
import pandas as pd 
import numpy as np 
import nbformat

import plotly.express as px 
import plotly.graph_objects as go 

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [24]:
# Creating a sample dataset for the model
X, y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [25]:
# Reviewing the created data
print("Input variables: ", X[0])
print("Target variables: ", y[0])

Input variables:  [-0.45451787 -1.25030969]
Target variables:  -82.51935822987818


In [26]:
# Transforming the data into Dataframe
data = pd.DataFrame({'feature_1': X[:, 0], 'feature_2': X[:, 1], 'target': y})
data

feature_1  feature_2      target
0   -0.454518  -1.250310  -82.519358
1   -0.823595  -0.931042 -194.943933
2   -1.133297   0.289697   73.287465
3    2.265215   1.597089  137.733264
4    1.566265   0.639704  118.059141
..        ...        ...         ...
95   0.436522   0.197334   31.427283
96   1.621610  -0.246115   15.629010
97  -0.718610  -0.569885  -21.409538
98  -0.763564  -0.378682 -120.725360
99  -0.179104  -1.698625 -216.701538

[100 rows x 3 columns]

In [27]:
# Visualizing the data
fig = px.scatter_3d(data, x='feature_1', y='feature_2', z='target')
fig.show()

In [28]:
# Spliting the dataset into Training and Testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

print("Shape of Independent Variable Training Set: ", X_train.shape)
print("Shape of Dependent Variable Training Set: ", y_train.shape)

print("Shape of Independent Variable Testing Set: ", X_test.shape)
print("Shape of Dependent Variable Testing Set: ", y_test.shape)

Shape of Independent Variable Training Set:  (80, 2)
Shape of Dependent Variable Training Set:  (80,)
Shape of Independent Variable Testing Set:  (20, 2)
Shape of Dependent Variable Testing Set:  (20,)


In [29]:
# creating an object of the linear regression model for prediction
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [30]:
# Training the model using the train set
model.fit(X_train, y_train)

LinearRegression()

In [31]:
# Using the trained model for prediction
model.predict(X_test)

array([  68.65650815,  -58.03566901,  117.27828438,  -80.05136689,
         -9.72295078,   78.73000646,  -56.41135087,  -51.11928065,
        -53.09489998,  108.32415608,   47.27452925,   12.50653604,
        -24.06766516,  -74.38568558,  -34.27348163,  -58.68790686,
        -31.51331241, -104.01175437,   41.34033025,   27.17509915])

In [32]:
y_test

array([  67.52968161,  -87.11108756,   81.3293378 ,  -81.81485672,
         15.6290104 ,   96.72223624, -120.72535989,  -12.18474936,
        -18.27490169,  120.14802815,   40.63033622,   59.7978214 ,
         54.10657236,  -21.40953841,   25.84063882,  -35.88162104,
        -97.86027036, -115.66970291,   81.21614279,  158.87700855])

In [33]:
# Visualizing the predicted place
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = model.predict(final).reshape(10, 10)

z = z_final


In [34]:
fig = px.scatter_3d(data, x='feature_1', y='feature_2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [35]:
# The coefficient of the expression
model.coef_

array([14.16445576, 97.33713334])

In [36]:
# The intercept values
model.intercept_

np.float64(-8.736042356203118)

In [37]:
# Trying the evalution metrices
y_pred = model.predict(X_test)

print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 38.93700904660605
MSE 2445.9191502125946
R2 score 0.6168875889028096
